### PR TITLE
Better error messages (fixes #12)

### LINKED ISSUE #12: Unclear error message when CAS is set to "Refuse Access"
### Description

Current error message when user logs in successfully via CAS but does not exist in Pressbooks AND CAS is configured to Refuse Access to new users is: "CAS authentication failed", which suggests the login info is wrong or some other server issue. 

This message should be changed to: 

> Unable to log in: You do not have an account on this Pressbooks network. 
> To request an account, please contact your institution's Pressbooks Network Manager: $network_manager_contact. 

 

Where $network_manager_contact is a string. Input is from a text box (that needs to be created) in the Network Settings that would let Network Managers specify name and email of a contact at their institution.

### Steps to Reproduce

1. Make sure your CAS user doesn't exist in Pb
2. Set CAS setting to "Refuse Access" to new users
3. Log in via CAS with user credentials

**Expected behavior:** 
Sensible error message

**Actual behavior:** 
"CAS authentication failed"

### PR DESCRIPTION
**Pull request by dac514**

### CODE REVIEW

File: inc/class-cas.php [hunk 1]
```diff
@@ -233,15 +239,34 @@ public function authenticate( $user, $username, $password ) {
...
+	 *
+	 * @see \Aldine\Helpers\handle_contact_form_submission for $email code
+	 *
+	 * @return string
+	 */
+	public function authenticationFailedMessage( $provision ) {
+		if ( $provision === 'refuse' ) {
+			$email = get_blog_option( get_main_site_id(), 'pb_network_contact_email', get_site_option( 'admin_email', '' ) );
+			$email = ( ! empty( $email ) ? ": {$email}" : '.' );
+			$message = sprintf( __( "Unable to log in: You do not have an account on this Pressbooks network. To request an account, please contact your institution's Pressbooks Network Manager", 'pressbooks-cas-sso' ), $email );
```
Comment (greatislander) [inline inc/class-cas.php]: Where is the `$email` value used in this function?

Comment (dac514) [reply inc/class-cas.php]: Doh. Thanks.

**Review by greatislander — APPROVED** [review]
