### PR TITLE
Tweak user flow after logging in via CAS (fix #9)

### LINKED ISSUE #9: User flow after logging in via CAS
### Description

Users are currently redirected to their dashboard after they log in via SSO, which is different from normal Pressbooks login, where they are redirected to the website frontend. This causes users to potentially land on non-optimal pages, such as error messages or book backends with inactive chapter links (if they are subscriber to a book).

NOTE: problem only occurs if user has no book. Once user has a book, they access the book admin interface. 

### Steps to Reproduce

1. Go to network homepage and log in via CAS
2. Try this for different network settings: Registration is disabled or User accounts may be registered => error message

**Expected behavior:** 
User redirected to front end (same as when logging into Pressbooks normally)

**Actual behavior:** 
User redirected to backend/book creation form/error message.

### PR DESCRIPTION
**Pull request by dac514**

### CODE REVIEW

File: inc/class-admin.php [hunk 1]
```diff
@@ -93,7 +93,7 @@ public function saveOptions() {
 	}
 
 	/**
-	 * @return array
+	 * @return array{server_version: string, server_hostname: string, server_port: int, server_path: path, provision: refuse, email_domain: string, button_text: string, bypass: bool, forced_redirection: bool}
```
Comment (greatislander) [inline inc/class-admin.php:96]: 🆒
